dico_attribut = {
    "cheveux": {
        "couleur": ["noir", "brun", "chatain", "blond", "roux"],
        "longueur": ["court", "mi_long", "long"],
        "texture": ["lisse", "ondule", "boucle", "frise"],
        "frange": ["Oui", "Non"]
    },
    "pilosite_faciale": {
        "barbe": ["Oui", "Non"],
        "moustache": ["Oui", "Non"]
    },
    "lunettes": ["Oui", "Non"],
    "accessoires_tete": ["Oui", "Non"],
    "vetements": {
        "type_haut": ["t_shirt", "sweat", "chemise", "veste", "maillot", "pull"],
        "couleur_haut": ["noir", "blanc", "gris", "vert", "bleu", "autre"],
        "style": ["decontracte", "formel", "sportif", "atypique"]
    },
    "expression": {
        "expression_visage": ["neutre", "sourire", "surpris", "amuse"],
        "bouche_ouverte": ["Oui", "Non"]
    },
    "photo": {
        "fond": ["lycee", "interieur", "exterieur"],
        "selfie": ["Oui", "Non"]
    },
    "image a un filtre": ["Oui", "Non"],
    "peau" : {"couleur" :["Clair", "Mate", "Foncé"]}
}

class Personne:
    def __init__(self, nom, attributs):
        self.nom = nom
        self.attributs = attributs

    def __repr__(self):
        return f"{self.nom}"

    def afficher(self):
        print(f"{self.nom}")
        for categorie, valeur in self.attributs.items():
            print(f"{categorie} : {valeur}")
        print("\n")
        
        
adam = Personne("Adam", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "blanc", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Oui"})
adriano = Personne("Adriano", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "t_shirt", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
anaelle = Personne("Anaelle", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "blond", "longueur": "long", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "sweat", "couleur_haut": "blanc", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Non"}, "image a un filtre": "Non"})
anasbee = Personne("Anasbee", {"peau" : {"couleur" : "Mate"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "maillot", "couleur_haut": "bleu", "style": "sportif"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
anasZ = Personne("AnasZ", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "noir", "longueur": "long", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "t_shirt", "couleur_haut": "vert", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
antoine = Personne("Antoine", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "mi_long", "texture": "lisse", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "veste", "couleur_haut": "gris", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
auriana = Personne("Auriana", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "blond", "longueur": "mi_long", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Oui", "vetements": {"type_haut": "pull", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Non"}, "image a un filtre": "Oui"})
axel = Personne("Axel", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "t_shirt", "couleur_haut": "autre", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
constance = Personne("Constance", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "blond", "longueur": "mi_long", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "blanc", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Oui"})
devon = Personne("Devon", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "blond", "longueur": "court", "texture": "lisse", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Oui"})
elodie = Personne("Elodie", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "mi_long", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "sweat", "couleur_haut": "gris", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
elyas = Personne("Elyas", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "bleu", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
francis = Personne("Francis", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "sweat", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
hamza = Personne("Hamza", {"peau" : {"couleur" : "Mate"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "gris", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
imrane = Personne("Imrane", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "pull", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Non"}, "image a un filtre": "Non"})
jayson = Personne("Jayson", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "mi_long", "texture": "lisse", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "veste", "couleur_haut": "vert", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Oui"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
jeremy = Personne("Jeremy", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "t_shirt", "couleur_haut": "vert", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Oui"})
kenzo = Personne("Kenzo", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "mi_long", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "chemise", "couleur_haut": "blanc", "style": "formel"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Non"}, "image a un filtre": "Non"})
kerian = Personne("Kerian", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "chatain", "longueur": "mi_long", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "veste", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "exterieur", "selfie": "Oui"}, "image a un filtre": "Oui"})
leo = Personne("Leo", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "mi_long", "texture": "boucle", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Oui", "vetements": {"type_haut": "sweat", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "exterieur", "selfie": "Oui"}, "image a un filtre": "Non"})
louis = Personne("Louis", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "chatain", "longueur": "mi_long", "texture": "ondule", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "t_shirt", "couleur_haut": "blanc", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Non"}, "image a un filtre": "Non"})
lucas = Personne("Lucas", {"peau" : {"couleur" : "Mate"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "surpris", "bouche_ouverte": "Oui"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
luka = Personne("Luka", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "t_shirt", "couleur_haut": "gris", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Non"}, "image a un filtre": "Non"})
miles = Personne("Miles", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "frise", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "veste", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
numa = Personne("Numa", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "chatain", "longueur": "mi_long", "texture": "ondule", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Non"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "bleu", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Oui"}, "image a un filtre": "Non"})
philippe = Personne("Philippe", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "noir", "longueur": "mi_long", "texture": "ondule", "frange": "Oui"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "veste", "couleur_haut": "noir", "style": "formel"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
quentin = Personne("Quentin", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "sweat", "couleur_haut": "noir", "style": "atypique"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
sami = Personne("Sami", {"peau" : {"couleur" : "Mate"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "boucle", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "t_shirt", "couleur_haut": "blanc", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
solal = Personne("Solal", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "ondule", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Non", "accessoires_tete": "Non", "vetements": {"type_haut": "t_shirt", "couleur_haut": "blanc", "style": "decontracte"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "lycee", "selfie": "Non"}, "image a un filtre": "Non"})
amelie = Personne("Amelie", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "long", "texture": "ondule", "frange": "Non"}, "pilosite_faciale": {"barbe": "Non", "moustache": "Non"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "chemise", "couleur_haut": "noir", "style": "formel"}, "expression": {"expression_visage": "sourire", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})
valentin = Personne("Valentin", {"peau" : {"couleur" : "Clair"},"cheveux": {"couleur": "brun", "longueur": "court", "texture": "ondule", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Non", "vetements": {"type_haut": "sweat", "couleur_haut": "noir", "style": "decontracte"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "exterieur", "selfie": "Oui"}, "image a un filtre": "Oui"})
zakaria = Personne("Zakaria", {"peau" : {"couleur" : "Mate"},"cheveux": {"couleur": "noir", "longueur": "court", "texture": "lisse", "frange": "Non"}, "pilosite_faciale": {"barbe": "Oui", "moustache": "Oui"}, "lunettes": "Oui", "accessoires_tete": "Oui", "vetements": {"type_haut": "maillot", "couleur_haut": "blanc", "style": "sportif"}, "expression": {"expression_visage": "neutre", "bouche_ouverte": "Non"}, "photo": {"fond": "interieur", "selfie": "Oui"}, "image a un filtre": "Non"})


PERSONNAGES = [adam, adriano, anaelle, anasbee, anasZ, antoine, auriana, axel, constance, devon, elodie, elyas, francis, hamza, imrane, jayson, jeremy, kenzo, kerian, leo, louis, lucas, luka, miles, numa, philippe, quentin, sami, solal, amelie, valentin, zakaria]
