All_Dico = {
    "cheveux" : {"couleur" : ["brun", "blond"], "longueur" : ["court"], "type" : ["raide"], "forme" : ["frise"]},
    "yeux" : {"couleur" : ["marron"], "taille" : ["petit"], "forme" : ["rond"], "position" : ["ecarté"], "sourcils" : ["fins"]},
    "visage" : {"forme" : ["ovale"], "teint" : ["clair"]},
    "bouche" : {"taille" : ["moyenne"], "forme" : ["fines"]},
    "nez" : {"taille" : ["moyen"], "forme" : ["droit"]},
    "oreilles" : {"taille" : ["moyenne"], "forme" : ["rondes"]},
    "barbe" : {"presence" : [False]},
    "moustache" : {"presence" : [False]},
    "accessoires" : {"lunettes" : [False], "chapeau" : [False], "boucle_d_oreille" : [False]}
}

PERSONNAGES={"Adam":{},
 "Adriano":{},
 "Anaelle":{},
 "Anasbee":{},
 "AnasZ":{},
 "Antoine":{},
 "Auriana":{},
 "Axel":{"cheveux" : {"couleur" : ["blond"]}},
 "Constance":{},
 "Devon":{},
 "Elodie":{},
"Elyas":{},
 "Francis":{},
  "Hamza":{},
  "Imrane":{},
  "Jayson":{},
  "Jeremy":{},
  "Kenzo":{"cheveux" : {"couleur" : ["brun"]}},
  "Kerian":{"cheveux" : {"couleur" : ["brun"]}},
   "Leo":{},
   "Louis":{},
  "Lucas":{},
  "Luka":{},           
  "Miles":{},
  "Numa":{},
  "Philippe":{},
  "Quentin":{},
  "Sami":{},
  "Solal":{},
   "Amelie":{},          
  "Valentin":{},
  "Zakaria":{}        
 }
